# texts.py
# All the words the bot says to customers, in three languages.
# To change any wording later, this is the only file that needs editing.

TEXTS = {
    "uz": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Metropia Coffee botiga xush kelibsiz! ☕\nSizning kofe joyingiz...",
        "menu_button": "📋 Menyu",
        "back_button": "⬅️ Orqaga",
        "checkout_button": "✅ Buyurtma berish",
        "stamps_button": "☕ Mening kartam",
        "cart_button": "🛒 Savat",
        "clear_cart_button": "🗑 Savatni tozalash",
        "cart_cleared": "Savat tozalandi.",
        "no_past_orders": "Hali buyurtmalaringiz yo'q.",
        "past_orders_header": "So'nggi buyurtmalaringiz:",
        "cart_empty": "Savatingiz bo'sh — avval menyudan biror narsa tanlang!",
        "menu_currently_empty": "Hozircha menyu bo'sh — birozdan so'ng qayta urinib ko'ring.",
        "choose_category": "Bo'limni tanlang:",
        "choose_temp": "Issiq yoki sovuq?",
        "temp_issiq": "🔥 Issiq",
        "temp_sovuq": "❄️ Sovuq",
        "choose_size": "Hajmni tanlang:",
        "add_topping": "🧋 Boba qo'shish (+{price} so'm)",
        "skip_topping": "O'tkazib yuborish",
        "added_to_cart": "{item} savatga qo'shildi ✅",
        "your_order": "Sizning buyurtmangiz:",
        "total": "Jami",
        "choose_payment_method": "Qanday to'lamoqchisiz?",
        "share_contact_prompt": "Buyurtmangiz uchun telefon raqamingizni ulashing.",
        "share_contact_button": "📱 Raqamni ulashish",
        "share_location_prompt": "Sizga eng yaqin filialni topish uchun joylashuvingizni ulashing.",
        "share_location_button": "📍 Joylashuvni ulashish",
        "nearest_branch": "Sizga eng yaqin filial: {branch}\n{address}",
        "pickup_reminder": "Buyurtmangizni oling: {branch}",
        "invoice_title": "Metropia Coffee buyurtmasi",
        "invoice_description": "Buyurtmangiz uchun to'lov.",
        "payment_success": "To'lov qabul qilindi! Buyurtma raqamingiz #{number} ☕",
        "order_already_claimed": "Bu buyurtma allaqachon boshqa xodim tomonidan olingan.",
        "payment_error": "Xatolik yuz berdi. Birozdan so'ng qayta urinib ko'ring.",
        "stamps_header": "Metropia Coffee — Sodiqlik kartasi",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nAmal qilish muddati: {date}",
        "stamps_none_yet": "Hali shtamplaringiz yo'q — birinchi xaridingiz kartangizni boshlaydi!",
        "loyalty_code_line": "Xodimga ko'rsatish uchun kodingiz: {code}",
        "cash_usage": "Foydalanish: /cash <@username yoki kod> <summa> [izoh]\nMasalan: /cash @aziz123 35000 Latte",
        "cash_username_not_found": "{username} topilmadi — mijoz botga hali /start bosmagan bo'lishi mumkin. Raqamli kodni so'rang yoki botni ochishini so'rang.",
        "cash_order_default_desc": "Naqd to'lov",
        "cash_recorded": "Buyurtma #{number} qayd etildi — {amount} so'm (naqd)",
        "cash_customer_earned_free": "🎉 Mijoz bepul kofe qozondi!",
        "cash_customer_card_restarted": "Mijozning oldingi kartasi muddati tugagan edi — yangi karta boshlandi.",
        "cash_customer_stamps": "Mijozning shtamplari: {stamps}/{total}",
        "cash_stamp_notice_customer": "Naqd xaridingiz uchun shtamp qo'shildi ☕",
        "pay_cash_button": "💵 Naqd to'layman",
        "cash_enter_amount_button": "💰 Summani kiritish",
        "cash_request_staff_text": "💵 Naqd to'lov so'rovi\n👤 {customer}",
        "cash_request_sent_customer": "Xodimlarga xabar yuborildi ✅",
        "cash_send_amount_prompt": "Summani so'mda yuboring (izoh ham qo'shishingiz mumkin, masalan: 35000 Latte):",
        "cash_invalid_amount": "Noto'g'ri summa — faqat raqam yuboring, masalan: 35000",
        "cash_payment_button": "💵 Naqd pul",
        "cash_confirm_received_button": "💵 Naqd pul qabul qilindi",
        "cash_awaiting_confirmation": "⏳ Xodim tasdiqlashini kutmoqda...",
        "cash_order_placed_customer": "Buyurtmangiz xodimlarga yuborildi. To'lovni qabul qilgach, shtampingiz qo'shiladi ☕",
        "cash_order_confirmed_customer": "To'lov tasdiqlandi! Buyurtma raqamingiz #{number} ☕",
        "free_coffee_ready": "🎉 BEPUL KOFE TAYYOR — buni xodimga ko'rsating!",
        "card_expired_notice": "Eski kartangiz muddati tugagan edi — bu xarid yangi kartani boshladi.",
        "broadcast_sent": "Yuborildi: {count} mijozga.",
        "not_authorized": "Bu buyruq faqat do'kon egasi uchun.",
        "admin_categories_header": "📂 Bo'limlar (menyuni boshqarish):",
        "admin_add_category_button": "➕ Bo'lim qo'shish",
        "admin_no_categories": "Hali bo'limlar yo'q.",
        "admin_send_name_uz": "Nomini o'zbek tilida yuboring:",
        "admin_send_name_ru": "Endi rus tilida yuboring:",
        "admin_send_name_en": "Endi ingliz tilida yuboring:",
        "admin_category_added": "Bo'lim qo'shildi ✅",
        "admin_category_updated": "Bo'lim yangilandi ✅",
        "admin_item_updated": "Mahsulot yangilandi ✅",
        "admin_add_item_button": "➕ Mahsulot qo'shish",
        "admin_rename_button": "✏️ Nomini o'zgartirish",
        "admin_delete_category_button": "🗑 Bo'limni o'chirish",
        "admin_back_button": "⬅️ Orqaga",
        "admin_cant_delete_category_has_items": "Avval bu bo'limdagi mahsulotlarni o'chiring yoki ko'chiring.",
        "admin_confirm_delete_category": "Bu bo'limni o'chirishga ishonchingiz komilmi?",
        "admin_category_deleted": "Bo'lim o'chirildi.",
        "admin_item_added": "Mahsulot qo'shildi ✅",
        "admin_item_deleted": "Mahsulot o'chirildi.",
        "admin_confirm_delete_item": "Bu mahsulotni butunlay o'chirishga ishonchingiz komilmi?",
        "admin_no_items": "Bu bo'limda hali mahsulot yo'q.",
        "admin_choose_temp_option": "Bu mahsulot qanday bo'ladi?",
        "admin_temp_hot_only": "🔥 Faqat issiq",
        "admin_temp_sovuq_only": "❄️ Faqat sovuq",
        "admin_temp_both": "🔥❄️ Ikkalasi ham",
        "admin_choose_size_option": "Hajm bormi?",
        "admin_size_single": "Bitta hajm",
        "admin_size_two": "Ikki hajm (M/L)",
        "admin_send_price_for": "{label} narxini so'mda yuboring (faqat raqam):",
        "admin_invalid_price": "Noto'g'ri narx — faqat raqam yuboring, masalan: 25000",
        "admin_topping_label": "Qo'shimcha (boba) varianti:",
        "admin_topping_on": "Yoqilgan ✅",
        "admin_topping_off": "O'chirilgan",
        "admin_toggle_topping_button": "🔁 Qo'shimcha variantini almashtirish",
        "admin_add_option_button": "➕ Yana narx varianti qo'shish",
        "admin_remove_option_button": "🗑 Narx variantini o'chirish",
        "admin_delete_item_button": "🗑 Mahsulotni butunlay o'chirish",
        "admin_cancel_button": "Bekor qilish",
        "admin_yes_delete_button": "Ha, o'chirish",
        "admin_price_updated": "Narx yangilandi ✅",
        "admin_option_deleted": "Variant o'chirildi.",
        "admin_send_new_price": "Yangi narxni so'mda yuboring:",
        "admin_item_header": "Mahsulot:",
        "admin_choose_option_to_remove": "Qaysi variantni o'chirish kerak?",
        "admin_description_label": "Tavsif:",
        "admin_description_none": "yo'q",
        "admin_edit_description_button": "📝 Tavsifni tahrirlash",
        "admin_send_description": "Ingredientlar yoki allergiya haqida matn yuboring (\"skip\" — o'chirish uchun):",
        "admin_description_updated": "Tavsif yangilandi ✅",
        "admin_setbundle_usage": "Foydalanish: /setbundle <kredit soni> <narx>\nMasalan: /setbundle 10 315000",
        "admin_bundle_set": "Bundle sozlandi: {credits} ta ichimlik — {price} so'm",
        "admin_winback_count": "{count} ta faol bo'lmagan mijoz ({days} kundan beri buyurtma bermagan). Xabar yuborish uchun: /winback {days} <xabar matni>",
        "admin_winback_sent": "{count} ta mijozga yuborildi.",
        "birthday_usage": "Foydalanish: /birthday DD-MM\nMasalan: /birthday 15-03",
        "birthday_invalid": "Noto'g'ri sana. Masalan: /birthday 15-03",
        "birthday_saved": "Tug'ilgan kuningiz saqlandi 🎂 Shu kuni sizga bepul ichimlik sovg'a qilamiz!",
        "birthday_gift_notice": "🎂 Tug'ilgan kuningiz muborak! Sizga bepul ichimlik sovg'a qildik ☕",
        "bundle_credits_remaining": "Qolgan kreditlaringiz: {credits}",
        "bundle_invoice_title": "Metropia Coffee — Bundle",
        "bundle_invoice_description": "{credits} ta ichimlik uchun bundle sotib olish.",
        "bundle_not_configured": "Bundle hozircha mavjud emas.",
        "bundle_not_enough_credits": "Kreditlaringiz yetarli emas.",
        "bundle_pay_button": "🎫 Bundle bilan to'lash ({credits} qoldi)",
        "bundle_purchased": "{credits} ta kredit qo'shildi! Jami: {total} ☕",
        "choose_fulfillment": "Olib ketasizmi yoki yetkazib berilsinmi?",
        "fulfillment_pickup_button": "🚶 Olib ketish",
        "fulfillment_delivery_button": "🚚 Yetkazib berish",
        "choose_pickup_time": "Qachon olib ketasiz?",
        "pickup_asap_button": "⚡ Tez orada",
        "pickup_15_button": "+15 daqiqa",
        "pickup_30_button": "+30 daqiqa",
        "pickup_60_button": "+1 soat",
        "delivery_address_saved": "Yetkazib berish manzili saqlandi ✅",
        "share_location_delivery_prompt": "Yetkazib berish uchun joylashuvingizni ulashing.",
        "rate_order_prompt": "Buyurtmangizni qanday baholaysiz?",
        "rating_thanks": "Rahmat! {stars}",
        "referral_bonus_notice": "🎉 Do'stingiz birinchi buyurtmasini berdi — sizga bonus shtamp qo'shildi!",
        "out_of_stock": "Hozircha mavjud emas",
        "ordering_paused_notice": "Hozircha buyurtmalar qabul qilinmayapti. Birozdan so'ng qayta urinib ko'ring.",
        "ask_notes": "Buyurtmangiz uchun izoh bormi? (masalan: \"shakarsiz\") Yo'q bo'lsa \"skip\" deb yozing.",
        "order_ready_notice": "☕ Buyurtmangiz tayyor! Filialdan olib keting.",
        "order_again_button": "🔁 Qayta buyurtma qilish",
        "items_added_to_cart": "Mahsulotlar savatga qo'shildi ✅",
        "admin_stock_label": "Mavjudligi:",
        "admin_stock_in": "Mavjud ✅",
        "admin_stock_out": "Tugagan ❌",
        "admin_toggle_stock_button": "🔁 Mavjudligini almashtirish",
        "admin_ordering_paused": "Buyurtmalar to'xtatildi. Mijozlar hozircha buyurtma bera olmaydi.",
        "admin_ordering_resumed": "Buyurtmalar qayta yoqildi.",
        "admin_report_header": "📊 Hisobot: {label}",
        "admin_report_orders": "Buyurtmalar soni",
        "admin_report_revenue": "Tushum",
        "admin_report_top_items": "Eng ko'p sotilganlar:",
        "admin_report_today": "Bugun",
        "admin_report_week": "So'nggi 7 kun",
    },
    "ru": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Добро пожаловать в Metropia Coffee! ☕\nВаше кофейное место...",
        "menu_button": "📋 Меню",
        "back_button": "⬅️ Назад",
        "checkout_button": "✅ Оформить заказ",
        "stamps_button": "☕ Моя карта",
        "cart_button": "🛒 Корзина",
        "clear_cart_button": "🗑 Очистить корзину",
        "cart_cleared": "Корзина очищена.",
        "no_past_orders": "У вас пока нет заказов.",
        "past_orders_header": "Ваши последние заказы:",
        "cart_empty": "Ваша корзина пуста — сначала выберите что-нибудь из меню!",
        "menu_currently_empty": "Меню пока пусто — попробуйте немного позже.",
        "choose_category": "Выберите раздел:",
        "choose_temp": "Горячий или холодный?",
        "temp_issiq": "🔥 Горячий",
        "temp_sovuq": "❄️ Холодный",
        "choose_size": "Выберите размер:",
        "add_topping": "🧋 Добавить бобу (+{price} сум)",
        "skip_topping": "Пропустить",
        "added_to_cart": "{item} добавлен в корзину ✅",
        "your_order": "Ваш заказ:",
        "total": "Итого",
        "choose_payment_method": "Как вы хотите оплатить?",
        "share_contact_prompt": "Поделитесь номером телефона для вашего заказа.",
        "share_contact_button": "📱 Поделиться номером",
        "share_location_prompt": "Поделитесь местоположением, чтобы найти ближайший к вам филиал.",
        "share_location_button": "📍 Поделиться местоположением",
        "nearest_branch": "Ближайший к вам филиал: {branch}\n{address}",
        "pickup_reminder": "Заберите заказ здесь: {branch}",
        "invoice_title": "Заказ в Metropia Coffee",
        "invoice_description": "Оплата вашего заказа.",
        "payment_success": "Оплата получена! Номер вашего заказа #{number} ☕",
        "order_already_claimed": "Этот заказ уже взял в работу другой сотрудник.",
        "payment_error": "Произошла ошибка. Попробуйте ещё раз через минуту.",
        "stamps_header": "Metropia Coffee — Карта лояльности",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nДействительна до: {date}",
        "stamps_none_yet": "Пока нет штампов — первая покупка начнёт вашу карту!",
        "loyalty_code_line": "Ваш код для сотрудника: {code}",
        "cash_usage": "Использование: /cash <@username или код> <сумма> [описание]\nНапример: /cash @aziz123 35000 Латте",
        "cash_username_not_found": "{username} не найден — возможно, клиент ещё не нажимал /start в боте. Спросите числовой код или попросите открыть бота.",
        "cash_order_default_desc": "Оплата наличными",
        "cash_recorded": "Заказ #{number} записан — {amount} сум (наличные)",
        "cash_customer_earned_free": "🎉 Клиент получил бесплатный кофе!",
        "cash_customer_card_restarted": "Предыдущая карта клиента истекла — начата новая карта.",
        "cash_customer_stamps": "Штампы клиента: {stamps}/{total}",
        "cash_stamp_notice_customer": "Штамп добавлен за покупку наличными ☕",
        "pay_cash_button": "💵 Оплачу наличными",
        "cash_enter_amount_button": "💰 Ввести сумму",
        "cash_request_staff_text": "💵 Запрос оплаты наличными\n👤 {customer}",
        "cash_request_sent_customer": "Сотрудники уведомлены ✅",
        "cash_send_amount_prompt": "Отправьте сумму в сумах (можно добавить описание, например: 35000 Латте):",
        "cash_invalid_amount": "Неверная сумма — отправьте только число, например: 35000",
        "cash_payment_button": "💵 Наличные",
        "cash_confirm_received_button": "💵 Наличные получены",
        "cash_awaiting_confirmation": "⏳ Ожидает подтверждения сотрудника...",
        "cash_order_placed_customer": "Ваш заказ отправлен сотрудникам. Штамп будет добавлен после подтверждения оплаты ☕",
        "cash_order_confirmed_customer": "Оплата подтверждена! Номер вашего заказа #{number} ☕",
        "free_coffee_ready": "🎉 БЕСПЛАТНЫЙ КОФЕ ГОТОВ — покажите это сотруднику!",
        "card_expired_notice": "Срок действия вашей предыдущей карты истёк — эта покупка начала новую карту.",
        "broadcast_sent": "Отправлено {count} клиентам.",
        "not_authorized": "Эта команда только для владельца.",
        "admin_categories_header": "📂 Разделы (управление меню):",
        "admin_add_category_button": "➕ Добавить раздел",
        "admin_no_categories": "Пока нет разделов.",
        "admin_send_name_uz": "Отправьте название на узбекском:",
        "admin_send_name_ru": "Теперь отправьте на русском:",
        "admin_send_name_en": "Теперь отправьте на английском:",
        "admin_category_added": "Раздел добавлен ✅",
        "admin_category_updated": "Раздел обновлён ✅",
        "admin_item_updated": "Товар обновлён ✅",
        "admin_add_item_button": "➕ Добавить товар",
        "admin_rename_button": "✏️ Изменить название",
        "admin_delete_category_button": "🗑 Удалить раздел",
        "admin_back_button": "⬅️ Назад",
        "admin_cant_delete_category_has_items": "Сначала удалите или перенесите товары из этого раздела.",
        "admin_confirm_delete_category": "Точно удалить этот раздел?",
        "admin_category_deleted": "Раздел удалён.",
        "admin_item_added": "Товар добавлен ✅",
        "admin_item_deleted": "Товар удалён.",
        "admin_confirm_delete_item": "Точно удалить этот товар полностью?",
        "admin_no_items": "В этом разделе пока нет товаров.",
        "admin_choose_temp_option": "Каким бывает этот товар?",
        "admin_temp_hot_only": "🔥 Только горячий",
        "admin_temp_sovuq_only": "❄️ Только холодный",
        "admin_temp_both": "🔥❄️ И то, и другое",
        "admin_choose_size_option": "Есть размеры?",
        "admin_size_single": "Один размер",
        "admin_size_two": "Два размера (M/L)",
        "admin_send_price_for": "Отправьте цену для {label} в сумах (только число):",
        "admin_invalid_price": "Неверная цена — отправьте только число, например: 25000",
        "admin_topping_label": "Опция добавки (боба):",
        "admin_topping_on": "Включена ✅",
        "admin_topping_off": "Выключена",
        "admin_toggle_topping_button": "🔁 Переключить опцию добавки",
        "admin_add_option_button": "➕ Добавить ещё вариант цены",
        "admin_remove_option_button": "🗑 Удалить вариант цены",
        "admin_delete_item_button": "🗑 Удалить товар полностью",
        "admin_cancel_button": "Отмена",
        "admin_yes_delete_button": "Да, удалить",
        "admin_price_updated": "Цена обновлена ✅",
        "admin_option_deleted": "Вариант удалён.",
        "admin_send_new_price": "Отправьте новую цену в сумах:",
        "admin_item_header": "Товар:",
        "admin_choose_option_to_remove": "Какой вариант удалить?",
        "admin_description_label": "Описание:",
        "admin_description_none": "нет",
        "admin_edit_description_button": "📝 Изменить описание",
        "admin_send_description": "Отправьте текст об ингредиентах или аллергенах (\"skip\" — чтобы убрать):",
        "admin_description_updated": "Описание обновлено ✅",
        "admin_setbundle_usage": "Использование: /setbundle <кол-во кредитов> <цена>\nНапример: /setbundle 10 315000",
        "admin_bundle_set": "Bundle настроен: {credits} напитков — {price} сум",
        "admin_winback_count": "{count} неактивных клиентов (не заказывали {days} дней). Чтобы отправить: /winback {days} <текст сообщения>",
        "admin_winback_sent": "Отправлено {count} клиентам.",
        "birthday_usage": "Использование: /birthday ДД-ММ\nНапример: /birthday 15-03",
        "birthday_invalid": "Неверная дата. Например: /birthday 15-03",
        "birthday_saved": "Ваш день рождения сохранён 🎂 В этот день вы получите бесплатный напиток!",
        "birthday_gift_notice": "🎂 С днём рождения! Дарим вам бесплатный напиток ☕",
        "bundle_credits_remaining": "Осталось кредитов: {credits}",
        "bundle_invoice_title": "Metropia Coffee — Bundle",
        "bundle_invoice_description": "Покупка пакета на {credits} напитков.",
        "bundle_not_configured": "Bundle пока недоступен.",
        "bundle_not_enough_credits": "Недостаточно кредитов.",
        "bundle_pay_button": "🎫 Оплатить bundle (осталось {credits})",
        "bundle_purchased": "Добавлено {credits} кредитов! Всего: {total} ☕",
        "choose_fulfillment": "Заберёте сами или доставка?",
        "fulfillment_pickup_button": "🚶 Самовывоз",
        "fulfillment_delivery_button": "🚚 Доставка",
        "choose_pickup_time": "Когда заберёте заказ?",
        "pickup_asap_button": "⚡ Как можно скорее",
        "pickup_15_button": "+15 минут",
        "pickup_30_button": "+30 минут",
        "pickup_60_button": "+1 час",
        "delivery_address_saved": "Адрес доставки сохранён ✅",
        "share_location_delivery_prompt": "Поделитесь местоположением для доставки.",
        "rate_order_prompt": "Как вы оцените свой заказ?",
        "rating_thanks": "Спасибо! {stars}",
        "referral_bonus_notice": "🎉 Ваш друг сделал первый заказ — вам начислен бонусный штамп!",
        "out_of_stock": "Сейчас недоступно",
        "ordering_paused_notice": "Заказы временно не принимаются. Попробуйте немного позже.",
        "ask_notes": "Есть пожелания к заказу? (например: \"без сахара\") Если нет — напишите \"skip\".",
        "order_ready_notice": "☕ Ваш заказ готов! Заберите его в филиале.",
        "order_again_button": "🔁 Повторить заказ",
        "items_added_to_cart": "Товары добавлены в корзину ✅",
        "admin_stock_label": "Наличие:",
        "admin_stock_in": "В наличии ✅",
        "admin_stock_out": "Закончилось ❌",
        "admin_toggle_stock_button": "🔁 Переключить наличие",
        "admin_ordering_paused": "Приём заказов остановлен. Клиенты пока не могут заказывать.",
        "admin_ordering_resumed": "Приём заказов возобновлён.",
        "admin_report_header": "📊 Отчёт: {label}",
        "admin_report_orders": "Количество заказов",
        "admin_report_revenue": "Выручка",
        "admin_report_top_items": "Топ продаж:",
        "admin_report_today": "Сегодня",
        "admin_report_week": "Последние 7 дней",
    },
    "en": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Welcome to Metropia Coffee! ☕\nYour coffee spot...",
        "menu_button": "📋 Menu",
        "back_button": "⬅️ Back",
        "checkout_button": "✅ Checkout",
        "stamps_button": "☕ My Card",
        "cart_button": "🛒 Cart",
        "clear_cart_button": "🗑 Clear cart",
        "cart_cleared": "Cart cleared.",
        "no_past_orders": "No past orders yet.",
        "past_orders_header": "Your recent orders:",
        "cart_empty": "Your cart is empty — add something from the menu first!",
        "menu_currently_empty": "The menu is empty right now — please check back shortly.",
        "choose_category": "Choose a section:",
        "choose_temp": "Hot or iced?",
        "temp_issiq": "🔥 Hot",
        "temp_sovuq": "❄️ Iced",
        "choose_size": "Choose a size:",
        "add_topping": "🧋 Add boba (+{price} so'm)",
        "skip_topping": "Skip",
        "added_to_cart": "{item} added to cart ✅",
        "your_order": "Your order:",
        "total": "Total",
        "choose_payment_method": "How would you like to pay?",
        "share_contact_prompt": "Share your phone number for your order.",
        "share_contact_button": "📱 Share number",
        "share_location_prompt": "Share your location so we can find the branch closest to you.",
        "share_location_button": "📍 Share location",
        "nearest_branch": "Closest branch to you: {branch}\n{address}",
        "pickup_reminder": "Pick up your order at: {branch}",
        "invoice_title": "Metropia Coffee order",
        "invoice_description": "Payment for your order.",
        "payment_success": "Payment received! Your order number is #{number} ☕",
        "order_already_claimed": "This order has already been claimed by another staff member.",
        "payment_error": "Something went wrong. Please try again in a moment.",
        "stamps_header": "Metropia Coffee — Loyalty Card",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nValid until: {date}",
        "stamps_none_yet": "No stamps yet — your first purchase starts your card!",
        "loyalty_code_line": "Your code to show staff: {code}",
        "cash_usage": "Usage: /cash <@username or code> <amount> [description]\nExample: /cash @aziz123 35000 Latte",
        "cash_username_not_found": "{username} not found — the customer may not have pressed /start in the bot yet. Ask for their numeric code, or have them open the bot once.",
        "cash_order_default_desc": "Cash payment",
        "cash_recorded": "Order #{number} recorded — {amount} so'm (cash)",
        "cash_customer_earned_free": "🎉 Customer just earned a free coffee!",
        "cash_customer_card_restarted": "Customer's previous card had expired — a new one just started.",
        "cash_customer_stamps": "Customer's stamps: {stamps}/{total}",
        "cash_stamp_notice_customer": "You got a stamp for your cash purchase ☕",
        "pay_cash_button": "💵 I'm paying cash",
        "cash_enter_amount_button": "💰 Enter amount",
        "cash_request_staff_text": "💵 Cash payment request\n👤 {customer}",
        "cash_request_sent_customer": "Staff have been notified ✅",
        "cash_send_amount_prompt": "Send the amount in so'm (you can add a description too, e.g. 35000 Latte):",
        "cash_invalid_amount": "Invalid amount — send just a number, like: 35000",
        "cash_payment_button": "💵 Cash",
        "cash_confirm_received_button": "💵 Cash received",
        "cash_awaiting_confirmation": "⏳ Awaiting staff confirmation...",
        "cash_order_placed_customer": "Your order was sent to staff. Your stamp will be added once payment is confirmed ☕",
        "cash_order_confirmed_customer": "Payment confirmed! Your order number is #{number} ☕",
        "free_coffee_ready": "🎉 FREE COFFEE READY — show this to staff!",
        "card_expired_notice": "Your previous card had expired — this purchase started a new one.",
        "broadcast_sent": "Sent to {count} customers.",
        "not_authorized": "This command is for the shop owner only.",
        "admin_categories_header": "📂 Sections (menu management):",
        "admin_add_category_button": "➕ Add section",
        "admin_no_categories": "No sections yet.",
        "admin_send_name_uz": "Send the name in Uzbek:",
        "admin_send_name_ru": "Now send it in Russian:",
        "admin_send_name_en": "Now send it in English:",
        "admin_category_added": "Section added ✅",
        "admin_category_updated": "Section updated ✅",
        "admin_item_updated": "Drink updated ✅",
        "admin_add_item_button": "➕ Add drink",
        "admin_rename_button": "✏️ Rename",
        "admin_delete_category_button": "🗑 Delete section",
        "admin_back_button": "⬅️ Back",
        "admin_cant_delete_category_has_items": "Delete or move the drinks in this section first.",
        "admin_confirm_delete_category": "Delete this section for good?",
        "admin_category_deleted": "Section deleted.",
        "admin_item_added": "Drink added ✅",
        "admin_item_deleted": "Drink deleted.",
        "admin_confirm_delete_item": "Delete this drink completely?",
        "admin_no_items": "No drinks in this section yet.",
        "admin_choose_temp_option": "How does this drink come?",
        "admin_temp_hot_only": "🔥 Hot only",
        "admin_temp_sovuq_only": "❄️ Iced only",
        "admin_temp_both": "🔥❄️ Both",
        "admin_choose_size_option": "Does it have sizes?",
        "admin_size_single": "One size",
        "admin_size_two": "Two sizes (M/L)",
        "admin_send_price_for": "Send the price for {label} in so'm (just the number):",
        "admin_invalid_price": "That's not a valid price — send just a number, like: 25000",
        "admin_topping_label": "Topping add-on option:",
        "admin_topping_on": "On ✅",
        "admin_topping_off": "Off",
        "admin_toggle_topping_button": "🔁 Toggle topping add-on",
        "admin_add_option_button": "➕ Add another price option",
        "admin_remove_option_button": "🗑 Remove a price option",
        "admin_delete_item_button": "🗑 Delete this drink completely",
        "admin_cancel_button": "Cancel",
        "admin_yes_delete_button": "Yes, delete",
        "admin_price_updated": "Price updated ✅",
        "admin_option_deleted": "Option deleted.",
        "admin_send_new_price": "Send the new price in so'm:",
        "admin_item_header": "Drink:",
        "admin_choose_option_to_remove": "Which option should be removed?",
        "admin_description_label": "Description:",
        "admin_description_none": "none",
        "admin_edit_description_button": "📝 Edit description",
        "admin_send_description": "Send text about ingredients or allergens (\"skip\" to remove it):",
        "admin_description_updated": "Description updated ✅",
        "admin_setbundle_usage": "Usage: /setbundle <credit count> <price>\nExample: /setbundle 10 315000",
        "admin_bundle_set": "Bundle set: {credits} drinks — {price} so'm",
        "admin_winback_count": "{count} inactive customers (haven't ordered in {days} days). To send: /winback {days} <message text>",
        "admin_winback_sent": "Sent to {count} customers.",
        "birthday_usage": "Usage: /birthday DD-MM\nExample: /birthday 15-03",
        "birthday_invalid": "Invalid date. Example: /birthday 15-03",
        "birthday_saved": "Your birthday is saved 🎂 You'll get a free drink that day!",
        "birthday_gift_notice": "🎂 Happy birthday! We've gifted you a free drink ☕",
        "bundle_credits_remaining": "Credits remaining: {credits}",
        "bundle_invoice_title": "Metropia Coffee — Bundle",
        "bundle_invoice_description": "Buying a bundle of {credits} drinks.",
        "bundle_not_configured": "Bundles aren't available yet.",
        "bundle_not_enough_credits": "You don't have enough credits.",
        "bundle_pay_button": "🎫 Pay with bundle ({credits} left)",
        "bundle_purchased": "{credits} credits added! Total: {total} ☕",
        "choose_fulfillment": "Pickup or delivery?",
        "fulfillment_pickup_button": "🚶 Pickup",
        "fulfillment_delivery_button": "🚚 Delivery",
        "choose_pickup_time": "When will you pick it up?",
        "pickup_asap_button": "⚡ ASAP",
        "pickup_15_button": "+15 min",
        "pickup_30_button": "+30 min",
        "pickup_60_button": "+1 hour",
        "delivery_address_saved": "Delivery address saved ✅",
        "share_location_delivery_prompt": "Share your location for delivery.",
        "rate_order_prompt": "How would you rate your order?",
        "rating_thanks": "Thanks! {stars}",
        "referral_bonus_notice": "🎉 Your friend just placed their first order — you got a bonus stamp!",
        "out_of_stock": "Currently unavailable",
        "ordering_paused_notice": "We're not accepting orders right now. Please try again shortly.",
        "ask_notes": "Any notes for your order? (e.g. \"no sugar\") Type \"skip\" if not.",
        "order_ready_notice": "☕ Your order is ready! Pick it up at the branch.",
        "order_again_button": "🔁 Order again",
        "items_added_to_cart": "Items added to cart ✅",
        "admin_stock_label": "Stock:",
        "admin_stock_in": "In stock ✅",
        "admin_stock_out": "Out of stock ❌",
        "admin_toggle_stock_button": "🔁 Toggle stock",
        "admin_ordering_paused": "Ordering paused. Customers can't place orders right now.",
        "admin_ordering_resumed": "Ordering resumed.",
        "admin_report_header": "📊 Report: {label}",
        "admin_report_orders": "Orders",
        "admin_report_revenue": "Revenue",
        "admin_report_top_items": "Top sellers:",
        "admin_report_today": "Today",
        "admin_report_week": "Last 7 days",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    """Look up a piece of text in the customer's language, filling in any {placeholders}."""
    text = TEXTS.get(lang, TEXTS["en"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
