# texts.py
# All the words the bot says to customers, in three languages.
# To change any wording later, this is the only file that needs editing.

TEXTS = {
    "uz": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Metropia Coffee botiga xush kelibsiz! ☕\nSizning kofe joyingiz...",
        "menu_button": "📋 Menyu",
        "checkout_button": "✅ Buyurtma berish",
        "stamps_button": "☕ Mening kartam",
        "cart_empty": "Savatingiz bo'sh — avval menyudan biror narsa tanlang!",
        "menu_currently_empty": "Hozircha menyu bo'sh — birozdan so'ng qayta urinib ko'ring.",
        "choose_category": "Bo'limni tanlang:",
        "choose_temp": "Issiq yoki sovuq?",
        "temp_issiq": "🔥 Issiq",
        "temp_sovuq": "❄️ Sovuq",
        "choose_size": "Hajmni tanlang:",
        "add_topping": "🧋 Boba qo'shish (+{price} so'm)",
        "skip_topping": "O'tkazib yuborish",
        "added_to_cart": "{item} savatga qo'shildi ✅",
        "your_order": "Sizning buyurtmangiz:",
        "total": "Jami",
        "choose_payment_method": "Qanday to'lamoqchisiz?",
        "invoice_title": "Metropia Coffee buyurtmasi",
        "invoice_description": "Buyurtmangiz uchun to'lov.",
        "payment_success": "To'lov qabul qilindi! Buyurtmangiz tayyorlanmoqda ☕",
        "payment_error": "Xatolik yuz berdi. Birozdan so'ng qayta urinib ko'ring.",
        "stamps_header": "Metropia Coffee — Sodiqlik kartasi",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nAmal qilish muddati: {date}",
        "stamps_none_yet": "Hali shtamplaringiz yo'q — birinchi xaridingiz kartangizni boshlaydi!",
        "free_coffee_ready": "🎉 BEPUL KOFE TAYYOR — buni xodimga ko'rsating!",
        "card_expired_notice": "Eski kartangiz muddati tugagan edi — bu xarid yangi kartani boshladi.",
        "broadcast_sent": "Yuborildi: {count} mijozga.",
        "not_authorized": "Bu buyruq faqat do'kon egasi uchun.",
        "admin_categories_header": "📂 Bo'limlar (menyuni boshqarish):",
        "admin_add_category_button": "➕ Bo'lim qo'shish",
        "admin_no_categories": "Hali bo'limlar yo'q.",
        "admin_send_name_uz": "Nomini o'zbek tilida yuboring:",
        "admin_send_name_ru": "Endi rus tilida yuboring:",
        "admin_send_name_en": "Endi ingliz tilida yuboring:",
        "admin_category_added": "Bo'lim qo'shildi ✅",
        "admin_category_updated": "Bo'lim yangilandi ✅",
        "admin_item_updated": "Mahsulot yangilandi ✅",
        "admin_add_item_button": "➕ Mahsulot qo'shish",
        "admin_rename_button": "✏️ Nomini o'zgartirish",
        "admin_delete_category_button": "🗑 Bo'limni o'chirish",
        "admin_back_button": "⬅️ Orqaga",
        "admin_cant_delete_category_has_items": "Avval bu bo'limdagi mahsulotlarni o'chiring yoki ko'chiring.",
        "admin_confirm_delete_category": "Bu bo'limni o'chirishga ishonchingiz komilmi?",
        "admin_category_deleted": "Bo'lim o'chirildi.",
        "admin_item_added": "Mahsulot qo'shildi ✅",
        "admin_item_deleted": "Mahsulot o'chirildi.",
        "admin_confirm_delete_item": "Bu mahsulotni butunlay o'chirishga ishonchingiz komilmi?",
        "admin_no_items": "Bu bo'limda hali mahsulot yo'q.",
        "admin_choose_temp_option": "Bu mahsulot qanday bo'ladi?",
        "admin_temp_hot_only": "🔥 Faqat issiq",
        "admin_temp_sovuq_only": "❄️ Faqat sovuq",
        "admin_temp_both": "🔥❄️ Ikkalasi ham",
        "admin_choose_size_option": "Hajm bormi?",
        "admin_size_single": "Bitta hajm",
        "admin_size_two": "Ikki hajm (M/L)",
        "admin_send_price_for": "{label} narxini so'mda yuboring (faqat raqam):",
        "admin_invalid_price": "Noto'g'ri narx — faqat raqam yuboring, masalan: 25000",
        "admin_topping_label": "Qo'shimcha (boba) varianti:",
        "admin_topping_on": "Yoqilgan ✅",
        "admin_topping_off": "O'chirilgan",
        "admin_toggle_topping_button": "🔁 Qo'shimcha variantini almashtirish",
        "admin_add_option_button": "➕ Yana narx varianti qo'shish",
        "admin_remove_option_button": "🗑 Narx variantini o'chirish",
        "admin_delete_item_button": "🗑 Mahsulotni butunlay o'chirish",
        "admin_cancel_button": "Bekor qilish",
        "admin_yes_delete_button": "Ha, o'chirish",
        "admin_price_updated": "Narx yangilandi ✅",
        "admin_option_deleted": "Variant o'chirildi.",
        "admin_send_new_price": "Yangi narxni so'mda yuboring:",
        "admin_item_header": "Mahsulot:",
        "admin_choose_option_to_remove": "Qaysi variantni o'chirish kerak?",
    },
    "ru": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Добро пожаловать в Metropia Coffee! ☕\nВаше кофейное место...",
        "menu_button": "📋 Меню",
        "checkout_button": "✅ Оформить заказ",
        "stamps_button": "☕ Моя карта",
        "cart_empty": "Ваша корзина пуста — сначала выберите что-нибудь из меню!",
        "menu_currently_empty": "Меню пока пусто — попробуйте немного позже.",
        "choose_category": "Выберите раздел:",
        "choose_temp": "Горячий или холодный?",
        "temp_issiq": "🔥 Горячий",
        "temp_sovuq": "❄️ Холодный",
        "choose_size": "Выберите размер:",
        "add_topping": "🧋 Добавить бобу (+{price} сум)",
        "skip_topping": "Пропустить",
        "added_to_cart": "{item} добавлен в корзину ✅",
        "your_order": "Ваш заказ:",
        "total": "Итого",
        "choose_payment_method": "Как вы хотите оплатить?",
        "invoice_title": "Заказ в Metropia Coffee",
        "invoice_description": "Оплата вашего заказа.",
        "payment_success": "Оплата получена! Ваш заказ готовится ☕",
        "payment_error": "Произошла ошибка. Попробуйте ещё раз через минуту.",
        "stamps_header": "Metropia Coffee — Карта лояльности",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nДействительна до: {date}",
        "stamps_none_yet": "Пока нет штампов — первая покупка начнёт вашу карту!",
        "free_coffee_ready": "🎉 БЕСПЛАТНЫЙ КОФЕ ГОТОВ — покажите это сотруднику!",
        "card_expired_notice": "Срок действия вашей предыдущей карты истёк — эта покупка начала новую карту.",
        "broadcast_sent": "Отправлено {count} клиентам.",
        "not_authorized": "Эта команда только для владельца.",
        "admin_categories_header": "📂 Разделы (управление меню):",
        "admin_add_category_button": "➕ Добавить раздел",
        "admin_no_categories": "Пока нет разделов.",
        "admin_send_name_uz": "Отправьте название на узбекском:",
        "admin_send_name_ru": "Теперь отправьте на русском:",
        "admin_send_name_en": "Теперь отправьте на английском:",
        "admin_category_added": "Раздел добавлен ✅",
        "admin_category_updated": "Раздел обновлён ✅",
        "admin_item_updated": "Товар обновлён ✅",
        "admin_add_item_button": "➕ Добавить товар",
        "admin_rename_button": "✏️ Изменить название",
        "admin_delete_category_button": "🗑 Удалить раздел",
        "admin_back_button": "⬅️ Назад",
        "admin_cant_delete_category_has_items": "Сначала удалите или перенесите товары из этого раздела.",
        "admin_confirm_delete_category": "Точно удалить этот раздел?",
        "admin_category_deleted": "Раздел удалён.",
        "admin_item_added": "Товар добавлен ✅",
        "admin_item_deleted": "Товар удалён.",
        "admin_confirm_delete_item": "Точно удалить этот товар полностью?",
        "admin_no_items": "В этом разделе пока нет товаров.",
        "admin_choose_temp_option": "Каким бывает этот товар?",
        "admin_temp_hot_only": "🔥 Только горячий",
        "admin_temp_sovuq_only": "❄️ Только холодный",
        "admin_temp_both": "🔥❄️ И то, и другое",
        "admin_choose_size_option": "Есть размеры?",
        "admin_size_single": "Один размер",
        "admin_size_two": "Два размера (M/L)",
        "admin_send_price_for": "Отправьте цену для {label} в сумах (только число):",
        "admin_invalid_price": "Неверная цена — отправьте только число, например: 25000",
        "admin_topping_label": "Опция добавки (боба):",
        "admin_topping_on": "Включена ✅",
        "admin_topping_off": "Выключена",
        "admin_toggle_topping_button": "🔁 Переключить опцию добавки",
        "admin_add_option_button": "➕ Добавить ещё вариант цены",
        "admin_remove_option_button": "🗑 Удалить вариант цены",
        "admin_delete_item_button": "🗑 Удалить товар полностью",
        "admin_cancel_button": "Отмена",
        "admin_yes_delete_button": "Да, удалить",
        "admin_price_updated": "Цена обновлена ✅",
        "admin_option_deleted": "Вариант удалён.",
        "admin_send_new_price": "Отправьте новую цену в сумах:",
        "admin_item_header": "Товар:",
        "admin_choose_option_to_remove": "Какой вариант удалить?",
    },
    "en": {
        "choose_language": "Tilni tanlang / Выберите язык / Choose language:",
        "welcome": "Welcome to Metropia Coffee! ☕\nYour coffee spot...",
        "menu_button": "📋 Menu",
        "checkout_button": "✅ Checkout",
        "stamps_button": "☕ My Card",
        "cart_empty": "Your cart is empty — add something from the menu first!",
        "menu_currently_empty": "The menu is empty right now — please check back shortly.",
        "choose_category": "Choose a section:",
        "choose_temp": "Hot or iced?",
        "temp_issiq": "🔥 Hot",
        "temp_sovuq": "❄️ Iced",
        "choose_size": "Choose a size:",
        "add_topping": "🧋 Add boba (+{price} so'm)",
        "skip_topping": "Skip",
        "added_to_cart": "{item} added to cart ✅",
        "your_order": "Your order:",
        "total": "Total",
        "choose_payment_method": "How would you like to pay?",
        "invoice_title": "Metropia Coffee order",
        "invoice_description": "Payment for your order.",
        "payment_success": "Payment received! Your order is being made ☕",
        "payment_error": "Something went wrong. Please try again in a moment.",
        "stamps_header": "Metropia Coffee — Loyalty Card",
        "stamps_progress": "{card}\n{stamps}/{total}",
        "stamps_valid_until": "\nValid until: {date}",
        "stamps_none_yet": "No stamps yet — your first purchase starts your card!",
        "free_coffee_ready": "🎉 FREE COFFEE READY — show this to staff!",
        "card_expired_notice": "Your previous card had expired — this purchase started a new one.",
        "broadcast_sent": "Sent to {count} customers.",
        "not_authorized": "This command is for the shop owner only.",
        "admin_categories_header": "📂 Sections (menu management):",
        "admin_add_category_button": "➕ Add section",
        "admin_no_categories": "No sections yet.",
        "admin_send_name_uz": "Send the name in Uzbek:",
        "admin_send_name_ru": "Now send it in Russian:",
        "admin_send_name_en": "Now send it in English:",
        "admin_category_added": "Section added ✅",
        "admin_category_updated": "Section updated ✅",
        "admin_item_updated": "Drink updated ✅",
        "admin_add_item_button": "➕ Add drink",
        "admin_rename_button": "✏️ Rename",
        "admin_delete_category_button": "🗑 Delete section",
        "admin_back_button": "⬅️ Back",
        "admin_cant_delete_category_has_items": "Delete or move the drinks in this section first.",
        "admin_confirm_delete_category": "Delete this section for good?",
        "admin_category_deleted": "Section deleted.",
        "admin_item_added": "Drink added ✅",
        "admin_item_deleted": "Drink deleted.",
        "admin_confirm_delete_item": "Delete this drink completely?",
        "admin_no_items": "No drinks in this section yet.",
        "admin_choose_temp_option": "How does this drink come?",
        "admin_temp_hot_only": "🔥 Hot only",
        "admin_temp_sovuq_only": "❄️ Iced only",
        "admin_temp_both": "🔥❄️ Both",
        "admin_choose_size_option": "Does it have sizes?",
        "admin_size_single": "One size",
        "admin_size_two": "Two sizes (M/L)",
        "admin_send_price_for": "Send the price for {label} in so'm (just the number):",
        "admin_invalid_price": "That's not a valid price — send just a number, like: 25000",
        "admin_topping_label": "Topping add-on option:",
        "admin_topping_on": "On ✅",
        "admin_topping_off": "Off",
        "admin_toggle_topping_button": "🔁 Toggle topping add-on",
        "admin_add_option_button": "➕ Add another price option",
        "admin_remove_option_button": "🗑 Remove a price option",
        "admin_delete_item_button": "🗑 Delete this drink completely",
        "admin_cancel_button": "Cancel",
        "admin_yes_delete_button": "Yes, delete",
        "admin_price_updated": "Price updated ✅",
        "admin_option_deleted": "Option deleted.",
        "admin_send_new_price": "Send the new price in so'm:",
        "admin_item_header": "Drink:",
        "admin_choose_option_to_remove": "Which option should be removed?",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    """Look up a piece of text in the customer's language, filling in any {placeholders}."""
    text = TEXTS.get(lang, TEXTS["en"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
